Repository RDFLib/rdflib, pull requests merged in 2018-10, with the labels that each got.

#744 Remove SPARQLWrapper dependency
  rdflib/plugin.py
  rdflib/plugins/sparql/results/csvresults.py
  rdflib/plugins/sparql/results/graph.py
  rdflib/plugins/sparql/results/jsonresults.py
  rdflib/plugins/sparql/results/tsvresults.py
  rdflib/plugins/sparql/results/xmlresults.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/plugins/stores/sparqlwrapper.py
  rdflib/query.py
  setup.py
Labels: SPARQL, cleanup, store

#862 Total order patch patch
  rdflib/term.py
  test/test_term.py
Labels: SPARQL, bug, in-resolution

#866 ClosedNamespace returns right exception for way of access
  rdflib/namespace.py
Labels: enhance
