Repository RDFLib/rdflib, pull requests merged in 2020-03, with the labels that each got.

#875 assign members to subjects instead of adding each member individually
  rdflib/plugins/serializers/turtle.py
Labels: enhance, serialization

#649 namespace.py fix compute_qname missing namespaces
  rdflib/namespace.py
  rdflib/plugins/serializers/rdfxml.py
  rdflib/plugins/serializers/xmlwriter.py
  test/n3/n3-writer-test-30.n3
  test/n3/n3-writer-test-31.n3
  test/test_n3_suite.py
  test/test_namespace.py
  test/test_roundtrip.py
  test/test_turtle_serialize.py
Labels: discussion, serialization, turtle-1.1

#979 Pr 388 redux
  rdflib/term.py
  test/test_hex_binary.py
  test/test_literal.py
Labels: enhancement

#970 Allows RDF terms introduced by JSON-LD 1.1
  rdflib/namespace.py
Labels: enhancement

#978 Pr 451 redux
  rdflib/term.py
  test/test_term.py
Labels: bug
