Repository RDFLib/rdflib, pull requests merged in 2020-05, with the labels that each got.

#1033 Set update endpoint similar to query endpoint for sparqlstore if only one is given
  rdflib/plugins/stores/sparqlstore.py
Labels: SPARQL, store

#931 Adding a wrapper for batching add() calls to a Graph
  rdflib/graph.py
  test/test_batch_add.py
Labels: enhancement

#1000 Namespaces improvements
  rdflib/__init__.py
  rdflib/namespace.py
Labels: cleanup, enhancement
