Repository RDFLib/rdflib, pull requests merged in 2022-08, with the labels that each got.

#2065 fix: issues with string destination handling in `{Graph,Result}.serialize`
  CHANGELOG.md
  rdflib/graph.py
  rdflib/query.py
  test/test_serializers/test_serializer.py
  test/test_sparql/test_result.py
  test/utils/destination.py
  test/utils/result.py
  tox.ini
Labels: core

#1968 add chunk serializer & tests
  CHANGELOG.md
  rdflib/plugins/serializers/nt.py
  rdflib/tools/chunk_serializer.py
  test/test_tools/test_chunk_serializer.py
  test/utils/path.py
Labels: review wanted

#2080 feat: Add type hints to rdflib.graph
  CHANGELOG.md
  devtools/diffrtpy.py
  docs/conf.py
  rdflib/graph.py
  rdflib/plugins/parsers/hext.py
  rdflib/plugins/stores/memory.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/store.py
  test/test_roundtrip.py
  test/test_serializers/test_serializer.py
  test/utils/dawg_manifest.py
  test/utils/manifest.py
  test/utils/sparql_checker.py
Labels: review wanted

#2082 docs: Add a contributing guide
  README.md
  docs/CONTRIBUTING.md
  docs/index.rst
Labels: good first issue, review wanted

#2087 ci: switch from 3.11.0-beta.4 to 3.11.0-rc.1
  .github/workflows/validate.yaml
Labels: good first issue, review wanted

#2093 test: Fix `exclude_lines` for coverage
  setup.cfg
Labels: good first issue, review wanted

#2089 test: convert more test from unittest to pytest
  test/test_parsers/test_parser.py
  test/test_parsers/test_trix_parse.py
  test/test_store/test_store_sparqlstore.py
  test/test_store/test_store_sparqlupdatestore_mock.py
Labels: review wanted

#2094 feat: add type hints to `rdflib.plugins.sparql.{algebra,operators}`
  CHANGELOG.md
  Taskfile.yml
  rdflib/plugins/sparql/algebra.py
  rdflib/plugins/sparql/operators.py
  test/test_issues/test_issue1043.py
  test/test_issues/test_issue910.py
Labels: review wanted

#2085 fix: issue with trig reference counting across graphs
  .editorconfig
  CHANGELOG.md
  Taskfile.yml
  rdflib/plugins/serializers/trig.py
  test/data/roundtrip/bnode_refs.trig
  test/test_roundtrip.py
Labels: review wanted

#2097 feat: add type hints to `rdflib.query` and related
  CHANGELOG.md
  rdflib/graph.py
  rdflib/plugin.py
  rdflib/plugins/sparql/results/csvresults.py
  rdflib/plugins/sparql/results/graph.py
  rdflib/plugins/sparql/results/jsonresults.py
  rdflib/plugins/sparql/results/rdfresults.py
  rdflib/plugins/sparql/results/tsvresults.py
  rdflib/plugins/sparql/results/txtresults.py
  rdflib/plugins/sparql/results/xmlresults.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/query.py
  test/test_misc/test_plugins.py
  test/test_sparql/test_forward_slash_escapes.py
  test/test_sparql/test_sparql.py
  test/test_sparql/test_tsvresults.py
  test/test_typing.py
  test/utils/sparql_checker.py
Labels: review wanted
