Repository RDFLib/rdflib, pull requests merged in 2022-05, with the labels that each got.

#1888 Improved mock HTTP Server
  test/test_graph/test_graph_http.py
  test/test_store/test_store_sparqlstore.py
  test/test_store/test_store_sparqlupdatestore_mock.py
  test/utils/__init__.py
  test/utils/httpservermock.py
  test/utils/test/test_httpservermock.py
Labels: testing, review wanted

#1895 test: add more graph variants highlighting bugs
  test/data/variants/diverse_quads-asserts.json
  test/data/variants/diverse_quads.jsonld
  test/data/variants/diverse_quads.nq
  test/data/variants/diverse_quads.trig
  test/data/variants/diverse_triples-asserts.json
  test/data/variants/diverse_triples.hext
  test/data/variants/diverse_triples.jsonld
  test/data/variants/diverse_triples.nt
  test/data/variants/diverse_triples.ttl
  test/data/variants/more_quads-asserts.json
  test/data/variants/more_quads.jsonld
  test/data/variants/more_quads.nq
  test/data/variants/more_quads.trig
  test/test_graph/test_variants.py
  test/test_roundtrip.py
Labels: testing, review wanted

#1896 test: Add more tests for test utilities
  test/utils/test/test_testutils.py
Labels: testing, review wanted

#1897 test: earlier assert rewrite for test utitlities
  test/conftest.py
Labels: testing, review wanted

#1915 Added test for example at CBD definition. Fixes #1914.
  test/data/spec/cbd/example_graph.rdf
  test/data/spec/cbd/example_graph_cbd.rdf
  test/test_graph/test_graph_cbd.py
Labels: review wanted

#1929 Added SPARQL unicode numeric codepoint escape tests
  test/data/suites/rdflib/sparql/manifest.ttl
  test/data/suites/rdflib/sparql/syn-codepoint-escape-01.rq
  test/data/suites/rdflib/sparql/syn-codepoint-escape-02.rq
  test/data/suites/rdflib/sparql/syn-codepoint-escape-03.rq
  test/data/suites/rdflib/sparql/syn-codepoint-escape-04.rq
  test/data/suites/rdflib/sparql/syn-codepoint-escape-bad.rq
  test/test_w3c_spec/test_sparql_w3c.py
Labels: review wanted

#1898 test: Add more tests for Graph serialize
  test/test_serializers/test_serializer.py
Labels: testing, review wanted

#1891 W3 test reorg
  test/data/suites/rdflib/sparql/manifest.ttl
Labels: review wanted

#1931 test: move `EARL` and `RDFT` namespaces to separate files
  test/test_w3c_spec/test_n3_w3c.py
  test/test_w3c_spec/test_nquads_w3c.py
  test/test_w3c_spec/test_nt_w3c.py
  test/test_w3c_spec/test_trig_w3c.py
  test/test_w3c_spec/test_turtle_w3c.py
  test/utils/_EARL.py
  test/utils/_RDFT.py
  test/utils/earl.py
  test/utils/manifest.py
  test/utils/namespace.py
Labels: review wanted

#1928 style: enable and baseline flakeheaven
  .flake8
  .flakeheaven.baseline
  .github/workflows/validate.yaml
  Dockerfile.devcontainer
  Taskfile.yml
  docs/developers.rst
  pyproject.toml
  requirements.dev.txt
  requirements.flake8.txt
  setup.cfg
  setup.py
  tox.ini
Labels: review wanted

#1934 Passing "generate" option through in compute_qname_strict
  rdflib/namespace/__init__.py
  test/test_namespacemanager.py
Labels: review wanted

#1933 build: add GitHub Actions to dependabot
  .github/dependabot.yml
Labels: review wanted

#1926 feat: add typing for `rdflib/plugins/sparql`
  pyproject.toml
  rdflib/plugins/sparql/evaluate.py
  rdflib/plugins/sparql/sparql.py
Labels: review wanted

#1894 Fix simple literals returned as NULL using SERVICE (issue #1278)
  rdflib/plugins/sparql/evaluate.py
  test/test_sparql/test_service.py
Labels: review wanted

#1935 feat: add tests and typing for `rdflib.utils.{get_tree,find_roots}`
  rdflib/util.py
  test/data/defined_namespaces/rdftest.ttl
  test/data/fetcher.py
  test/test_util.py
  test/utils/graph.py
Labels: review wanted

#1870 Literal datetime sub
  rdflib/term.py
  test/test_literal/test_duration.py
  test/test_literal/test_literal.py
  test/utils/__init__.py
  test/utils/test/test_testutils.py
Labels: review wanted

#1858 fix: two issues with the N3 serializer
  rdflib/plugins/serializers/n3.py
  test/test_n3_formula.py
  test/test_roundtrip.py
  test/test_serializers/test_serializer_n3.py
  test/utils/__init__.py
  test/utils/test/test_testutils.py
Labels: review wanted, N3

#1887 Fix `None`/undefined handing in GROUP_CONCAT
  rdflib/plugins/sparql/aggregates.py
  test/test_sparql/test_sparql.py
Labels: SPARQL, review wanted

#1952 edit tabs to spaces
  test/test_sparql/test_datetime_processing.py
Labels: review wanted

#1956 test: convert `test_graph_http.py` to pytest
  test/test_graph/test_graph_http.py
Labels: review wanted

#1872 Add tests demonstrating forward-slash behaviors in Turtle, JSON-LD, and SPARQL
  test/data/variants/forward_slash-asserts.json
  test/data/variants/forward_slash-variant-prefixed.jsonld
  test/data/variants/forward_slash-variant-prefixed.ttl
  test/data/variants/forward_slash.jsonld
  test/data/variants/forward_slash.nt
  test/data/variants/forward_slash.ttl
  test/test_graph/test_variants.py
  test/test_sparql/test_forward_slash_escapes.py
Labels: review wanted

#1901 Fix for #1824 `s,http://rdlib.net,http://rdflib.net,g`
  rdflib/graph.py
  rdflib/parser.py
  rdflib/term.py
  test/jsonld/test_localsuite.py
  test/test_dataset/test_dataset.py
  test/test_graph/test_skolemization.py
  test/test_skolem_genid.py
  test/test_w3c_spec/test_rdfxml_w3c.py
Labels: review wanted

#1902 Fixes #1429, add `iri2uri`
  pyproject.toml
  rdflib/__init__.py
  rdflib/graph.py
  rdflib/parser.py
  rdflib/util.py
  test/test_graph/test_graph_http.py
  test/test_util.py
Labels: review wanted

#1961 test: convert `test/jsonld/test_util.py` to pytest
  test/jsonld/test_util.py
Labels: review wanted

#1962 style: fix/ingore some flake8 errors in `rdflib/graph.py`
  rdflib/graph.py
Labels: review wanted

#1963 test: fix `None` comparisons
  test/jsonld/test_context.py
  test/test_namespace/test_namespace.py
Labels: review wanted

#1964 style: fix/ignore flake8 errors in `rdflib/plugins/sparql/`
  rdflib/plugins/sparql/__init__.py
  rdflib/plugins/sparql/algebra.py
  rdflib/plugins/sparql/datatypes.py
  rdflib/plugins/sparql/evaluate.py
  rdflib/plugins/sparql/evalutils.py
  rdflib/plugins/sparql/operators.py
  rdflib/plugins/sparql/parser.py
  rdflib/plugins/sparql/parserutils.py
  rdflib/plugins/sparql/results/jsonresults.py
  rdflib/plugins/sparql/results/tsvresults.py
  rdflib/plugins/sparql/sparql.py
  rdflib/plugins/sparql/update.py
Labels: review wanted

#1943 fix outmoded `x and x or y` idiom in `infixowl.py`
  rdflib/extras/infixowl.py
Labels: review wanted

#1945 fix for sonarcloud-reported bug
  rdflib/plugins/serializers/trix.py
Labels: review wanted

#1951 fix sonarcloud-reported bug in xmlwriter, add test
  rdflib/plugins/serializers/xmlwriter.py
  test/test_serializers/test_xmlwriter_qname.py
Labels: review wanted

#1853 More type hints for `rdflib.graph` and related
  rdflib/compare.py
  rdflib/graph.py
  rdflib/paths.py
  rdflib/plugins/parsers/ntriples.py
  rdflib/plugins/serializers/rdfxml.py
  rdflib/util.py
  test/plugins/parser/example/rdflib/plugin/parser/__init__.py
  test/test_graph/test_canonicalization.py
  test/test_graph/test_diff.py
  test/test_namespace/test_namespace.py
  test/test_roundtrip.py
  test/test_typing.py
  test/utils/__init__.py
  test/utils/earl.py
Labels: review wanted

#1965 Add more typing for SPARQL
  rdflib/plugins/sparql/algebra.py
  rdflib/plugins/sparql/parserutils.py
Labels: review wanted

#1970 build: speed up flake8 by ignoring test data
  setup.cfg
Labels: review wanted

#1971 style: fix/ignore flake8 errors in store related code
  rdflib/plugins/stores/auditable.py
  rdflib/plugins/stores/berkeleydb.py
  rdflib/plugins/stores/concurrent.py
  rdflib/plugins/stores/memory.py
  rdflib/plugins/stores/regexmatching.py
  rdflib/plugins/stores/sparqlconnector.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/store.py
Labels: review wanted
