Repository RDFLib/rdflib, pull requests merged in 2023-09, with the labels that each got.

#2564 test: convert more unittest based tests to pytest
  test/test_issues/test_issue1141.py
  test/test_issues/test_issue1160.py
  test/test_issues/test_issue160.py
  test/test_issues/test_issue200.py
  test/test_issues/test_issue247.py
  test/test_issues/test_issue655.py
  test/test_issues/test_issue733.py
  test/test_issues/test_issue801.py
  test/test_issues/test_issue910.py
  test/test_issues/test_issue920.py
  test/test_issues/test_issue953.py
Labels: review wanted, ready to merge

#2565 style: fix more linting/ruff issues in tests
  pyproject.toml
  test/test_literal/test_uriref_literal_comparison.py
  test/test_nt_misc.py
  test/test_sparql/test_datetime_processing.py
  test/test_sparql/test_expressions.py
  test/test_sparql/test_initbindings.py
  test/test_store/test_store_sparqlstore.py
  test/test_store/test_store_sparqlupdatestore.py
Labels: review wanted, ready to merge

#2575 style: homogenize docstrings
  rdflib/collection.py
  rdflib/events.py
  rdflib/extras/describer.py
  rdflib/extras/external_graph_libs.py
  rdflib/extras/infixowl.py
  rdflib/graph.py
  rdflib/namespace/__init__.py
  rdflib/paths.py
  rdflib/plugins/parsers/ntriples.py
  rdflib/plugins/sparql/aggregates.py
  rdflib/plugins/sparql/algebra.py
  rdflib/plugins/sparql/datatypes.py
  rdflib/plugins/sparql/evaluate.py
  rdflib/plugins/sparql/operators.py
  rdflib/plugins/sparql/parserutils.py
  rdflib/plugins/sparql/results/csvresults.py
  rdflib/plugins/sparql/results/jsonresults.py
  rdflib/plugins/sparql/results/xmlresults.py
  rdflib/serializer.py
  rdflib/store.py
  rdflib/term.py
  rdflib/tools/defined_namespace_creator.py
  rdflib/util.py
  test/test_graph/test_graph_cbd.py
  test/test_roundtrip.py
Labels: documentation

#2577 build: fix minimum version testing
  .github/workflows/validate.yaml
  docs/developers.rst
  pyproject.toml
  tox.ini
Labels: review wanted

#2383 Issue 2378 goal: Get CI to pass without ALLOW_UNICODE on doctests
  pyproject.toml
Labels: documentation, fix
