Repository RDFLib/rdflib, pull requests merged in 2023-07, with the labels that each got.

#2468 trig Parser now raises SyntaxError, when finding nested graphs
  rdflib/plugins/parsers/trig.py
  test/test_w3c_spec/test_trig_w3c.py
  test_reports/rdflib_w3c_trig-HEAD.ttl
Labels: review wanted, ready to merge

#2471 Mark one sparql10 test as skipped (term-6)
  test/test_w3c_spec/test_sparql10_w3c.py
  test_reports/rdflib_w3c_sparql10-HEAD.ttl
Labels: review wanted, ready to merge

#2469 trig GRAPH needs graphname (as in w3c-test:trig-graph-bad-01)
  rdflib/plugins/parsers/trig.py
  test/test_w3c_spec/test_trig_w3c.py
  test_reports/rdflib_w3c_trig-HEAD.ttl
Labels: review wanted, ready to merge

#2472 test: Modernize literal tests
  test/test_literal/test_literal.py
Labels: testing, review wanted, ready to merge

#2474 added test and bugfix for the custom groupconcat separator "" (issue#2473)
  rdflib/plugins/sparql/aggregates.py
  test/test_sparql/test_translate_algebra.py
Labels: review wanted, ready to merge

#2476 test: add helper for parameterized outcome tests
  test/test_graph/test_graph.py
  test/test_literal/test_literal.py
  test/test_misc/test_input_source.py
  test/test_misc/test_networking_redirect.py
  test/test_namespace/test_namespace.py
  test/test_namespace/test_namespacemanager.py
  test/test_sparql/test_prefixed_name.py
  test/test_sparql/test_service.py
  test/utils/exceptions.py
  test/utils/literal.py
  test/utils/outcome.py
  test/utils/test/test_outcome.py
Labels: testing, review wanted, ready to merge

#2485 test: reuse example namespaces
  test/test_dataset/test_dataset.py
  test/test_graph/test_diff.py
  test/test_graph/test_graph_http.py
  test/test_graph/test_skolemization.py
  test/test_issues/test_issue1043.py
  test/test_issues/test_issue1484.py
  test/test_issues/test_issue274.py
  test/test_issues/test_issue381.py
  test/test_issues/test_issue563.py
  test/test_issues/test_issue733.py
  test/test_issues/test_issue801.py
  test/test_literal/test_literal.py
  test/test_misc/test_security.py
  test/test_parsers/test_parser_turtlelike.py
  test/test_serializers/test_serializer.py
  test/test_serializers/test_serializer_jsonld.py
  test/test_serializers/test_serializer_n3.py
  test/test_sparql/test_initbindings.py
  test/test_sparql/test_sparql.py
  test/test_store/test_store_auditable.py
  test/test_store/test_store_sparqlupdatestore_mock.py
  test/test_turtle_quoting.py
  test/utils/namespace/__init__.py
Labels: testing, review wanted, ready to merge

#2500 Longturtle improvements
  docs/plugin_serializers.rst
  rdflib/plugins/serializers/longturtle.py
  test/test_serializers/test_serializer_longturtle.py
Labels: review wanted, ready to merge

#2467 Modify TriG serializer to not generate new prefixes for graph URIs
  rdflib/plugins/serializers/trig.py
  test/test_trig.py
Labels: review wanted, ready to merge

#2504 Corrected n3 method of path objects (fixes #2503)
  rdflib/paths.py
  test/test_path.py
Labels: review wanted, fix, core, ready to merge, concept: property path
