Repository RDFLib/rdflib, pull requests merged in 2023-05, with the labels that each got.

#2389 fix: HTTP 308 Permanent Redirect status code handling
  rdflib/_networking.py
  rdflib/parser.py
  test/conftest.py
  test/data.py
  test/data/defined_namespaces/adms.rdf
  test/data/defined_namespaces/adms.ttl
  test/data/defined_namespaces/rdfs.rdf
  test/data/fetcher.py
  test/test_graph/test_graph.py
  test/test_graph/test_graph_redirect.py
  test/test_misc/test_input_source.py
  test/test_misc/test_networking_redirect.py
  test/utils/exceptions.py
  test/utils/http.py
  test/utils/httpfileserver.py
Labels: review wanted, ready to merge

#2391 docs: recommend making an issue before making an enchancement
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CONTRIBUTING.md
  docs/developers.rst
Labels: documentation, review wanted, ready to merge

#2384 Issue 2378: Remove unicode string form in rdflib/term.py
  rdflib/term.py
Labels: documentation, review wanted, ready to merge

#2365 fix handling of URIs in the default namespace
  rdflib/namespace/__init__.py
  test/test_namespace/test_namespacemanager.py
  test/utils/exceptions.py
Labels: review wanted, ready to merge, awaiting feedback
