Repository RDFLib/rdflib, pull requests merged in 2023-08, with the labels that each got.

#2517 Fix nested list expansion in JSON-LD
  rdflib/plugins/parsers/jsonld.py
  test/jsonld/test_nested_arrays.py
Labels: review wanted, ready to merge

#2539 test: add skips to accommodate a DBpedia outage
  test/test_examples.py
  test/test_sparql/test_service.py
Labels: testing, review wanted, ready to merge

#2540 test: make graph variant tests more granular
  test/data/variants/blank_and_base_prefix-meta.json
  test/data/variants/diverse_quads-meta.json
  test/data/variants/diverse_triples-meta.json
  test/data/variants/forward_slash-meta.json
  test/data/variants/more_quads-meta.json
  test/data/variants/rdf11trig_eg2-meta.json
  test/data/variants/rdf_prefix-meta.json
  test/data/variants/schema_only_base-meta.json
  test/data/variants/simple_quad-meta.json
  test/data/variants/simple_triple-meta.json
  test/data/variants/special_chars-meta.json
  test/data/variants/xml_literal-meta.json
  test/test_graph/test_variants.py
  test/utils/dawg_manifest.py
  test/utils/graph.py
Labels: review wanted, ready to merge

#2543 test: add more accommodation for DBpedia issues
  test/test_sparql/test_service.py
Labels: testing, review wanted, networking, ready to merge

#2544 test: add python variants to variant based tests
  test/data.py
  test/data/variants/diverse_quads-variant-typed.jsonld
  test/data/variants/diverse_quads-variant-typed.nq
  test/data/variants/diverse_quads.py
  test/data/variants/diverse_triples.py
  test/data/variants/simple_quad.py
  test/data/variants/simple_triple.py
  test/test_graph/test_graph_redirect.py
  test/test_graph/test_variants.py
  test/utils/graph.py
Labels: review wanted, ready to merge

#2547 build: remove unused setuptools setting
  setup.cfg
Labels: review wanted, ready to merge

#2553 fix: remove `print()` calls from SPARQL algebra code
  rdflib/plugins/sparql/algebra.py
Labels: review wanted, ready to merge

#2546 fix: `queryGraph` selection for `query` and `update`
  rdflib/graph.py
  test/test_graph/test_graph_store.py
Labels: SPARQL, store, review wanted, ready to merge

#2554 fix: SPARQL `LOAD ... INTO GRAPH` handling
  rdflib/plugins/sparql/sparql.py
  rdflib/plugins/sparql/update.py
  test/data/variants/relative_triple-meta.json
  test/data/variants/relative_triple.nt
  test/data/variants/relative_triple.ttl
  test/test_sparql/test_update.py
  test/utils/__init__.py
  test/utils/graph.py
Labels: review wanted, ready to merge

#2559 style: Fix linting errors in serializer tests
  pyproject.toml
  test/test_serializers/test_prettyxml.py
  test/test_serializers/test_serializer_turtle.py
  test/test_serializers/test_serializer_xml.py
Labels: review wanted, ready to merge

#2562 test: migrate some tests from unittest to pytest
  test/test_issues/test_issue1043.py
  test/test_issues/test_issue1484.py
  test/test_issues/test_issue161.py
  test/test_issues/test_issue209.py
  test/test_issues/test_issue248.py
  test/test_issues/test_issue977.py
Labels: review wanted, ready to merge

#2561 style: fix the naming of test data constants
  test/data.py
  test/test_conjunctivegraph/test_conjunctivegraph_operator_combinations.py
  test/test_dataset/test_dataset.py
  test/test_dataset/test_dataset_generators.py
  test/test_extras/test_infixowl/test_basic.py
  test/test_extras/test_infixowl/test_class.py
  test/test_extras/test_infixowl/test_cover.py
  test/test_extras/test_infixowl/test_individual.py
  test/test_graph/test_graph.py
  test/test_graph/test_graph_generators.py
  test/test_graph/test_namespace_rebinding.py
  test/test_graph/test_slice.py
  test/test_store/test_store_sparqlupdatestore.py
Labels: review wanted, ready to merge
