Repository RDFLib/rdflib, pull requests merged in 2023-04, with the labels that each got.

#2323 Widen `Graph.__contains__` type hint
  rdflib/graph.py
Labels: review wanted, ready to merge

#2301 Streamline typing and implementation of SPARQL processor
  rdflib/plugins/sparql/evaluate.py
  rdflib/plugins/sparql/processor.py
  rdflib/plugins/sparql/update.py
Labels: SPARQL, review wanted

#2334 build: unify poetry version source
  .github/workflows/docker-images.yaml
  .github/workflows/validate.yaml
  .pre-commit-config.yaml
  devtools/requirements-poetry.in
Labels: review wanted, ready to merge

#2336 refactor: eliminate unneeded `rdflib.compat` imports
  rdflib/compat.py
  rdflib/plugins/sparql/sparql.py
Labels: review wanted, ready to merge, refactor

#2337 refactor: eliminate unused imports
  rdflib/__init__.py
  rdflib/namespace/__init__.py
Labels: review wanted, ready to merge, refactor

#2338 refactor: narrow imports
  rdflib/extras/infixowl.py
  rdflib/plugins/sparql/parserutils.py
  rdflib/void.py
Labels: review wanted, ready to merge, refactor

#2339 refactor: eliminate inheritance from object
  rdflib/collection.py
  rdflib/compare.py
  rdflib/container.py
  rdflib/events.py
  rdflib/extras/describer.py
  rdflib/extras/infixowl.py
  rdflib/graph.py
  rdflib/namespace/__init__.py
  rdflib/parser.py
  rdflib/paths.py
  rdflib/plugins/parsers/jsonld.py
  rdflib/plugins/parsers/notation3.py
  rdflib/plugins/parsers/ntriples.py
  rdflib/plugins/parsers/rdfxml.py
  rdflib/plugins/serializers/jsonld.py
  rdflib/plugins/serializers/xmlwriter.py
  rdflib/plugins/shared/jsonld/context.py
  rdflib/plugins/sparql/aggregates.py
  rdflib/plugins/sparql/parserutils.py
  rdflib/plugins/sparql/sparql.py
  rdflib/plugins/stores/concurrent.py
  rdflib/plugins/stores/sparqlconnector.py
  rdflib/query.py
  rdflib/resource.py
  rdflib/store.py
  rdflib/term.py
  rdflib/tools/csv2rdf.py
  test/test_graph/test_batch_add.py
  test/test_nt_misc.py
  test/test_parsers/test_swap_n3.py
  test/test_serializers/test_prettyxml.py
  test/test_serializers/test_serializer_xml.py
Labels: review wanted, ready to merge, refactor

#2322 Add optional graph argument to Graph.cbd, use for DESCRIBE queries
  rdflib/graph.py
  rdflib/plugins/sparql/evaluate.py
  test/test_graph/test_graph_cbd.py
Labels: review wanted, ready to merge

#2340 fix: correct imports and `__all__`
  docs/conf.py
  docs/rdf_terms.rst
  pyproject.toml
  rdflib/namespace/_GEO.py
  rdflib/namespace/__init__.py
  rdflib/plugins/stores/sparqlconnector.py
  rdflib/plugins/stores/sparqlstore.py
  test/jsonld/runner.py
  test/jsonld/test_api.py
  test/jsonld/test_compaction.py
  test/jsonld/test_context.py
  test/jsonld/test_named_graphs.py
  test/test_dataset/test_dataset.py
  test/test_graph/test_graph.py
  test/test_graph/test_graph_context.py
  test/test_graph/test_graph_http.py
  test/test_namespace/test_namespace.py
  test/test_roundtrip.py
  test/test_sparql/test_service.py
  test/test_store/test_store_sparqlstore.py
  test/test_store/test_store_sparqlstore_query.py
  test/test_store/test_store_sparqlstore_sparqlconnector.py
  test/test_store/test_store_sparqlupdatestore_mock.py
  test/utils/httpfileserver.py
  test/utils/test/test_httpservermock.py
Labels: review wanted, ready to merge

#2350 fix: eliminate bare `except:`
  rdflib/namespace/__init__.py
  rdflib/plugins/parsers/notation3.py
  rdflib/plugins/parsers/trix.py
  rdflib/plugins/serializers/longturtle.py
  rdflib/plugins/serializers/rdfxml.py
  rdflib/plugins/serializers/turtle.py
  rdflib/query.py
  rdflib/tools/csv2rdf.py
  rdflib/tools/rdf2dot.py
  rdflib/tools/rdfs2dot.py
Labels: review wanted, ready to merge
