Repository RDFLib/rdflib, pull requests merged in 2025-09, with the labels that each got.

#3075 Specify `Optional` parameters in `Graph.triples_choices`
  rdflib/graph.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/store.py
Labels: 7.1

#3221 [7.x] notation3.py: don't normalize float representation
  rdflib/plugins/parsers/notation3.py
  test/test_n3.py
Labels: 7.x

#2796 SPARQL result parsing
  rdflib/plugin.py
  rdflib/plugins/stores/sparqlconnector.py
  rdflib/plugins/stores/sparqlstore.py
  rdflib/util.py
Labels: enhancement, awaiting feedback
